package edu.ycp.cs320.cspath1.enums;

public enum SolicitationType {
	ME_CAPSTONE,
	ECE_CAPSTONE,
	CivE_CAPSTONE,
	ME_ECE_CAPSTONE,
	SW_ENGINEERING,
	CS_SENIOR_DESIGN_I,
	CS_SENIOR_DESIGN_II,
	INDEPENDENT_STUDY,
	CS_INTERNSHIP,
	ENGINEERING_COOP,
	CLASS_PROJECT
}
